### ISSUE TITLE
Controller generates pdbs and pdb watchers

### ISSUE THREAD

**Issue by paulgmiller** [paulgmiller/k8s-pdb-autoscaler#11]
Two parts
tr
1) A controller should watch some/all namespaces for pdbs and when a pdb is found it should try and sicover the target deployment.  This should remove the func (r *PDBWatcherReconciler) discoverDeployment funcion from the PDBWatcherReconciler which only does part of the job.

2) it could also find deployments with max surge and creates a pdb with minavailable just less than the replicas? (but should it change over time? 

Could do the same for stateful sets but riskier.

**Comment by skuchipudi295** [comment]
code completed and tested
